"""empty message

Revision ID: 3ca20fcd4ae6
Revises: ec8a13c5ada9
Create Date: 2022-04-11 10:29:48.366668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "3ca20fcd4ae6"
down_revision = "ec8a13c5ada9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("doctor_ibfk_1", "doctor", type_="foreignkey")
    op.drop_column("doctor", "user_id")
    op.add_column("user", sa.Column("doctor_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "user", "doctor", ["doctor_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_column("user", "doctor_id")
    op.add_column(
        "doctor",
        sa.Column("user_id", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key("doctor_ibfk_1", "doctor", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###
