"""add_patietn_id

Revision ID: 759bbffee888
Revises: 3ca20fcd4ae6
Create Date: 2022-04-13 11:25:13.101614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '759bbffee888'
down_revision = '3ca20fcd4ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('patient_ibfk_2', 'patient', type_='foreignkey')
    op.drop_column('patient', 'user_id')
    op.add_column('user', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'patient', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'patient_id')
    op.add_column('patient', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('patient_ibfk_2', 'patient', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
