"""Add patient

Revision ID: 9c0170622b8a
Revises: 69c66a8e1ffc
Create Date: 2022-03-24 01:01:11.687626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c0170622b8a"
down_revision = "69c66a8e1ffc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "address",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country", sa.String(length=32), nullable=True),
        sa.Column("city", sa.String(length=32), nullable=True),
        sa.Column("street", sa.String(length=32), nullable=True),
        sa.Column("house_number", sa.String(length=16), nullable=True),
        sa.Column("number_flat", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "patient",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=32), nullable=True),
        sa.Column("surname", sa.String(length=32), nullable=True),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("address_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["address.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_patient_surname"), "patient", ["surname"], unique=False)
    op.create_table(
        "phone",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country_code", sa.Integer(), nullable=True),
        sa.Column("area_code", sa.Integer(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("phone")
    op.drop_index(op.f("ix_patient_surname"), table_name="patient")
    op.drop_table("patient")
    op.drop_table("address")
    # ### end Alembic commands ###
